"""updated review model

Revision ID: d976c949e907
Revises: 8cb2ebe66b49
Create Date: 2025-08-31 14:51:49.515981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd976c949e907'
down_revision: Union[str, Sequence[str], None] = '8cb2ebe66b49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'end_time')
    op.drop_column('sessions', 'start_time')
    # ### end Alembic commands ###
